version: "3.8"
services:
  backend:
    build: ./music-backend
    ports:
      - "5000:5000"
    volumes:
      - ./music-backend:/app

  frontend:
    build: ./music-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./music-frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
